name = "vilfintv-subscribe-worker"
main = "subscribe-worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

[[d1_databases]]
binding = "DB"
database_name = "subscribers-db"
database_id = "0bdd24a2-6109-4225-a873-90c216c530ab"
