name = "vilfintv-subscribe-worker"
main = "subscribe-worker.js"
compatibility_date = "2024-12-01"
workers_dev = true

# To deploy this worker, run:
# npx wrangler deploy -c wrangler.subscribe.toml

# To set the GitHub PAT, run:
# npx wrangler secret put GITHUB_PAT -c wrangler.subscribe.toml
